version: '3.5'

services:

  redis:
    image: redis:5-alpine
    container_name: cmf-redis
    ports:
      - 6380:6379

  api:
    image: node:17.6-alpine
    container_name: cmf-api
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
