version: '3.5'

services:

  cmf-redis:
    image: redis:5-alpine
    container_name: redis
    ports:
      - 6380:6379

  cmf-api:
    image: node:17.6-alpine
    container_name: api
    working_dir: /app
    volumes:
      - ./:/app
      - ./node_modules/:/node_modules
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"
